export const IPC_CHANNELS = {
  getStatus: 'impeller:system:get-status',
  ping: 'impeller:system:ping',
  restart: 'impeller:system:restart',
  openLog: 'impeller:system:open-log',
  statusChanged: 'impeller:system:status-changed',
  closeRequested: 'impeller:system:close-requested',
  closeAcknowledged: 'impeller:system:close-acknowledged',
  confirmClose: 'impeller:system:confirm-close',
  cancelClose: 'impeller:system:cancel-close',
  projectCreate: 'impeller:project:create',
  projectOpen: 'impeller:project:open',
  projectOpenRecent: 'impeller:project:open-recent',
  projectClose: 'impeller:project:close',
  projectReleaseLocalWorkspace: 'impeller:project:release-local-workspace',
  projectGetOverview: 'impeller:project:get-overview',
  projectUpdateMetadata: 'impeller:project:update-metadata',
  projectCreateBackup: 'impeller:project:create-backup',
  projectListRecent: 'impeller:project:list-recent',
} as const;
